resources:
- deployment.yaml
- service.yaml
images:
- name: hello-fastapi
  newName: opjorr/prova-devops
  newTag: b98b8fae67268e1824a15c39304cd48c932ee3de
- name: opjorr/prova-devops
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
